version: "3.9"
services:
  wp_app:
    depends_on:
      - wp_db
    image: wordpress:6.5.3-php8.2-fpm
    container_name: wp_app
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=wp_db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=$MYSQL_DATABASE
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network

  wp_db:
    container_name: wp_db
    image: mysql:8.1
    restart: always
    env_file: .env
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    networks:
      - app-network

  wp_nginx:
    container_name: wp_nginx
    image: nginx:1.21-alpine
    depends_on:
      - wp_db
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certbot-etc:/etc/letsencrypt
    networks:
      - app-network

  certbot:
    depends_on:
      - webserver
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-etc:/etc/letsencrypt
      - ./wordpress:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email vng.tuantd2@gmail.com --agree-tos --no-eff-email --staging -d clematisperfume.click -d www.clematisperfume.click
networks:
  app-network:
    driver: bridge